name: Pnpm release
on:
  push:
    branches:
      - main
permissions:
    contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v2
    - uses: 90dy/gha-pnpm-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
